vars:
  fluentd_input:
    - { type: "tail", path: "/var/log/httpd/wordpress-access_log", pos_file: "/var/log/td-agent/tmp/apache.access.wordpress.log.pos", tag: "apache.access.wordpress" }
    - { type: "tail", path: "/var/log/httpd/photoblog-accesslog", pos_file: "/var/log/td-agent/tmp/apache.access.photoblog.log.pos", tag: "apache.access.photoblog" }
    
  fluentd_output:
    - { match_tag: "apache.access.*", match_path: "/var/log/td-agent/apache.access" } 

tasks:

- name: Put td-agent conf
  template:
    src: ../../common/templates/td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
